# Generated by Django 3.0.5 on 2022-12-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commentor_name',
        ),
    ]
